# -*- coding: utf-8 -*-
"""latex_ocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rn94opOYVIB-irV5cnpM_Z_JBEHblcf2
"""

#

pip install "pix2tex[gui]"

!pip install fastapi
!pip install kaleido
!pip install python-multipart

!pip install uvicorn

!pip install streamlit

!python -m pix2tex.api.run

!!git clone https://github.com/lukas-blecher/LaTeX-OCR.git

# Commented out IPython magic to ensure Python compatibility.
# %cd LaTeX-OCR

!python setup.py install

# Commented out IPython magic to ensure Python compatibility.
# %cd pix2tex

from cli import main

class Args:
    temperature = 0.333
    config = 'settings/config.yaml'
    checkpoint = 'model/checkpoints/weights.pth'
    no_cuda = False
    no_resize = False
    show = False
    katex = False
    gui = False
    file = ['/content/LaTeX-OCR/pix2tex/test.jpg']  # replace with your image path

args = Args()

# main(args)

from PIL import Image
from pix2tex.cli import LatexOCR

model = LatexOCR()
img = Image.open('/content/test3.PNG')

print(model(img))